---
# file: tasks/main.yml
#
# Install Prometheus apache-exporter.
#
# @see http://prometheus.io/docs/introduction/getting_started/
#

- block:

    - name: set internal variables for convenience
      set_fact:
        prometheus_apache_exporter_git_url: "github.com/neezgee/apache_exporter"
        prometheus_apache_exporter_subdir: "{{ prometheus_install_path }}/apache_exporter"


- block:

    - name: set internal variables for convenience
      set_fact:
        prometheus_apache_exporter_daemon_dir: "{{ prometheus_install_path }}/apache_exporter"

    - name: create needed dirs
      file: path={{ item }}  state=directory
      with_items:
        - "{{ apache_exporter_goroot }}"
        - "{{ apache_exporter_gopath }}"
        - "{{ prometheus_apache_exporter_daemon_dir }}"

    - name: build apache_exporter
      command: /usr/local/go/bin/go get {{ prometheus_apache_exporter_git_url }}
      args:
        chdir: "{{ prometheus_install_path }}"
        creates: apache_exporter
      environment:
        GO15VENDOREXPERIMENT: 1
        GOROOT: "{{ apache_exporter_goroot }}"
        GOPATH: "{{ apache_exporter_gopath }}"
        PATH: "{{ ansible_env.PATH }}:{{ apache_exporter_goroot }}/bin:{{ apache_exporter_gopath }}/bin"

- name: copy the built node_exporter to the install path
  command: "cp {{ apache_exporter_gopath }}/bin/apache_exporter {{ prometheus_apache_exporter_daemon_dir }}"
  args:
    creates: "{{ prometheus_apache_exporter_daemon_dir }}/apache/exporter"

- name: set permissions, owner and group
  file: path={{ prometheus_apache_exporter_daemon_dir }}/apache_exporter owner={{ prometheus_user }} group={{ prometheus_group }} mode="go-w"

- name: copy the built node_exporter to the install path
  command: "cp {{ apache_exporter_gopath }}/bin/apache_exporter {{ prometheus_install_path }}/apache_exporter/"
  args:
    creates: "{{ prometheus_apache_exporter_daemon_dir }}"


- name: set apache_exporter variables
  copy: src="../files/etc-default-apache_exporter"  dest=/etc/default/apache_exporter

- name: copy INIT script to server
  template: src="../templates/apache_exporter.sysvinit.{{ ansible_os_family|lower }}.sh.j2"  dest="/etc/init.d/apache_exporter"  mode="a+x"
  when: not prometheus_apache_exporter_use_systemd|bool

- name: copy systemd config to server
  template: src="../templates/apache_exporter.service.j2"  dest="/lib/systemd/system/apache_exporter.service"
  when: prometheus_apache_exporter_use_systemd


- name: set INIT status and start
  service: name=apache_exporter enabled=yes state=started
