---
# file: tasks/main.yml
# Top-level installer for Apache exporter.
#
# @see https://github.com/prometheus/prometheus
# @see http://prometheus.io/docs/introduction/getting_started/
#

- name: set role variables, if necessary
  include: set-role-variables.yml

- name: install apache-exporter
  include: install-apache-exporter.yml
  when: '"node_exporter" in prometheus_components'
